config/routes.rb
Rails.application.routes.draw do
  root :to => 'interviews#index'
  resources :questions

  resources :interviews
  
  post 'interviews/new_question' => "interviews#new_question"
  
  post '/interviews/delete_question' => "interviews#delete_question"

  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/interview.rb
class Interview < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all    
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy, :new_question, :delete_question]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
    @questions = Question.where("interview = ?", @interview.company)
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
    @companies = getCompanies
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new
    @interview.company = Company.find(params[:company]).name

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #Add a new question to this interview
  def new_question
    question = Question.new
    question.question = params[:question]
    question.interview = @interview.company
    question.save
    
    redirect_to @interview
  end
  
  def delete_question
    #@interview = Interview.find(params[:interview])
    Question.find(params[:question]).destroy
    
    redirect_to @interview
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:company)
    end
  
  def getCompanies
    companies = Array.new
    Company.all.each do |company|
      companies.push([company.name, company.id])
    end
    return companies
  end
  
  
  
  #Scroll space!!!
  
  
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.interview = params[:interview]

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/interviews/_form.html.erb
<%= form_for(@interview) do |f| %>
  <% if @interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% @interview.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= select_tag(:company, options_for_select(@companies)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<h1 class="text-center">Interviews</h1>


<% @interviews.each_with_index do |interview, index| %>
<% if index % 2 == 0 %>
    <div class="row items second_row">  
      <% else %>
        <div class="row items"> 
      <% end %>
          <%= link_to interview.company, interview, class: "item_link" %>

      <div class="buttons pull-right">        
      
          <%= link_to edit_interview_path(interview) do %>
            <i class="fa fa-edit fa-2x"></i> 
          <% end %>

          <%= link_to interview, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-close fa-2x"></i> 
          <% end %>
        </div>
      </div>
    <% end %>
<br>

      <%= link_to 'New Interview', new_interview_path, class: "btn btn-default" %>

app/views/interviews/new.html.erb
<h1>New interview</h1>

<%= render 'form' %>

<%= link_to 'Back', interviews_path, class: "btn btn-default" %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>


<h1 class="text-center"><%= @interview.company %></h1>

<div class="content">
  <% @questions.each_with_index do |question, index| %>
  <% if index % 2 != 0 %>
    <div class="row question">
      <% else %>
      <div class="row question second_row">
      <% end %>
      <%= form_tag( "./delete_question", method: "post") do %>
      <span class="item_text"><i class="fa fa-angle-right"></i><%= question.question %></span>
      <%= hidden_field_tag(:id, @interview.id) %>
      <%= hidden_field_tag(:question, question.id) %>
        <%= button_tag("Delete", class: "pull-right btn btn-default delete_btn") do %>
        <i class="fa fa-close"></i> 
    <% end %>
    <% end %></div>
    <% end %> 
</div>

<%= form_tag( "./new_question", method: "post") do %>
  <%= hidden_field_tag(:id, @interview.id) %>
  <%= text_field_tag(:question) %>
  <%= submit_tag("Add", class: "btn btn-default") %>
<% end %>

<%= link_to 'Edit', edit_interview_path(@interview), class: "btn btn-default" %>
<%= link_to 'Back', interviews_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- 
      If you are looking at this maybe you want to hire me?
      Get in touch at: portfolio.johnarmstrong.co

      Created by John Armstrong 2014
  -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>InterviewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  
  <!-- Icons. fontawesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="navbar-inner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a id="brand" class="navbar-brand" href="http://portfolio.johnarmstrong.co">JOHN ARMSTRONG</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul id="links" class="nav navbar-nav navbar-right">
                        <li><a href="../interviews">Home</a>
                        </li>
                        <li><a href="../companies">Companies</a>                    
                        </li>
                        <li><a href="../interviews">Interviews</a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
  
<div class="container main">
 <%= yield %> 
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>